### ISSUE TITLE
deepExtend modifies objects by reference

### ISSUE THREAD

**Issue by jonjaques** [kurtmilam/underscoreDeepExtend#10]
Hello,

I'm experiencing what I would consider unexpected behavior in that deepExtend modifies objects other than the first argument.

This is what happens:
```javascript
var defaults = { foo: 'bar' };
var combined = deepExtend({}, defaults, { bar: 'baz' });
log(combined) // { foo: 'bar', bar: 'baz' };
log(defaults) // { foo: 'bar', bar: 'baz' };
```

What I would expect (based on Underscore docs, behavior of jQuery.extend): `defaults` should remain intact.
```javascript
var defaults = { foo: 'bar' };
var combined = deepExtend({}, defaults, { bar: 'baz' });
log(combined) // { foo: 'bar', bar: 'baz' };
log(defaults) // { foo: 'bar' };
```

Here's a snippet from the underscore docs. 

**_.extend(destination, *sources)**
Copy all of the properties in the source objects over to the destination object, and return the destination object. It's in-order, so the last source will override properties of the same name in previous arguments.

```
_.extend({name: 'moe'}, {age: 50});
=>  {name: 'moe', age: 50}
```

**Comment by kurtmilam** [comment]
Thanks for the report. I'm not able to reproduce the behavior you've described (tested on Chrome '40.0.2214.93 m' and Firefox 35.0.1 running on Windows 8.1 Pro 64bit. Could you put together a working fiddle for me to look at, and tell me which browser you're seeing this in?

Here's [my attempt to reproduce the behavior you've described](http://jsfiddle.net/texinwien/rkkfsqce/1/), including a comparison to straight `lodash.extend()` (results displayed in console).

They seem to work in exactly the same way, to me.

**Comment by jonjaques** [comment]
Thank you for putting that fiddle together (I probably should have done that first). I was using _.mixin too, so that may have had something to do with it? I will try to extract this out of my project tomorrow.

**Comment by kurtmilam** [comment]
No worries. I'll be interested to see what you come up with. Someone else has reported similar behavior over on my gist where published the first simple version of this little function: https://gist.github.com/kurtmilam/1868955#comment-1356616

I don't think using it as a mixin would make a difference. May see if I can update the fiddle with a mixin test, as well, just to make sure.

**Comment by kurtmilam** [comment]
@jonjaques: Hold off on your fiddle. I tried a few more combinations based on the bug reported on my Gist and was able to confirm an issue using slightly different test code than you provided.

I'm testing a fix for the issue now. It's likely that this fix will address the issue you were seeing in your code.
