### ISSUE TITLE
Transfer NPM ownership?

### ISSUE THREAD

**Issue by pygy** [kurtmilam/underscoreDeepExtend#14]
@kurtmilam: Would you be interested in managing the NPM module as well?

After setup, admin is as complicated as updating the package version according to semver (but since we're still in 0.x.y territory you can do whatever you like (-;) and running `npm publish` from your local directory.

Looking into this, it looks like you must create a npm account so that I can add you the the owner list.

https://docs.npmjs.com/cli/owner

**Comment by kurtmilam** [comment]
Sure, that would be fine.

Anything I need to do on my end?

Kurt

**Comment by pygy** [comment]
I need to know your NPM user name. You may have to [sign up](https://www.npmjs.com/signup).

**Comment by pygy** [comment]
Where are we with this? I don't remember if we ever transferred the account...

**Comment by kurtmilam** [comment]
Hi Pierre,

I must have missed your previous email somehow.

I'm in the middle of moving to a new place, but I'll get you my npm user
name asap.

Thanks for following up.

Kurt

**Comment by pygy** [comment]
No worries, ping me when you have the time :-)

**Comment by pygy** [comment]
This package has been exploding since last summer: http://npm-stat.com/charts.html?package=underscore-deep-extend

30k installs in January...

Ready for the transfer?

**Comment by kurtmilam** [comment]
I am. My wife and I moved in December and had our first child at the end of
January,  so I've been a little distracted recently.

Cool to hear that the package is getting popular,  and thanks for following
up again on it.

You need my npm user name,  is that correct?

Thanks,
Kurt

**Comment by pygy** [comment]
Congratulations to both of you :-)

> You need my npm user name,  is that correct?

Indeed.

**Comment by kurtmilam** [comment]
Thanks!

User name is xioup .

Let me know if you need anything else.

Kurt

**Comment by pygy** [comment]
Here you are, now it's all yours.

**Comment by kurtmilam** [comment]
Thanks!

**Comment by kurtmilam** [comment]
Hi Pierre,

Any chance you could unregister the package at bower so I can keep it
up-to-date there, as well?

It looks like 'bower unregister underscore-deep-extend' would do the trick
if you're logged in.

There's a CURL option you could use, as well, since you're the owner of the
original github repo. More here:
http://stackoverflow.com/questions/27858666/moving-the-github-repo-thats-a-bower-package

I'd like to coordinate the timing with you, if at all possible, to make
sure I can successfully register it immediately after you unregister it.
I'm located in Austria, Central European time, FYI.

Thanks,
Kurt

**Comment by pygy** [comment]
I'm looking into it. I had completely forgotten about the Bower thing, and haven't logged in in ages. Hopefully it works...

**Comment by pygy** [comment]
Mixed news: I'm (very) tired and only read the beginning of your post before trying to unregister. I can't remember the password, so I tried the cURL method, which doesn't work either...

So I can't unregister right now, but at least, my ham fisted attempt doesn't leave the name free to be snatched.

I'll open an issue over at bower.

**Comment by pygy** [comment]
Oh, did you try to unregister using the `cURL` method?

You can generate a token over at https://github.com/settings/tokens

Sorry for the trouble...
