### ISSUE TITLE
NPM package is out of date

### ISSUE THREAD

**Issue by pete-thompson** [kurtmilam/underscoreDeepExtend#15]
Hi, it appears that the current NPM package is out of date. It hasn't been updated to point to this Github repository, which means it's missing the last fix (cloning objects to avoid modifying parameters).

**Comment by kurtmilam** [comment]
Hi, I just published to the NPM repository.

It's my first time to publish to the NPM repository, so here's to hoping I got it right.

**Comment by pete-thompson** [comment]
Awesome - thanks for sorting :)
